### ISSUE TITLE
pressing a shitload of buttons at once...

### ISSUE THREAD

**Issue by MparkG** [billthefarmer/melodeon#3]
... makes the audio clip..
i have just seen a note talking about the app using an external midi synth, so idk how feasible this is to normalized/limit..
Anyhow, farmer, i suddenly find you behind many good audio apps on fdroid, very nicely done!

**Comment by billthefarmer** [comment]
Depends on the instrument and how well the multitouch works. Will be the same in my [Accordion](https://github.com/billthefarmer/accordion) app as it's identical apart from the buttons. Anyway, IMHO, I don't believe that either of these apps are realistically playable because when held correctly you can't see the buttons and can't feel them either.

I've yet to witness anyone claiming to play it whereas there exists a [video](https://www.youtube.com/watch?v=JXFDcEOhIX8) of someone playing the [Windows](https://github.com/billthefarmer/c-melodeon) version.
