### ISSUE TITLE
Cant get back to Melodeon after change instrument

### ISSUE THREAD

**Issue by rogercreagh** [billthefarmer/melodeon#6]
V1.17 has a setting to select different voices with Melodeon selected at the top of the list. If you change to a different voice then Melodeon is no longer in the list, but everything else is.
The only way to get back is to uninstall and reinstall.

**Comment by billthefarmer** [comment]
There is no such thing as a 'Melodeon' midi instrument, which is why the app defaults to 'Accordion'. [That part](https://github.com/billthefarmer/melodeon/tree/master/src/main/res) of the app has not changed for 4 years. Not reproducible.

![Screenshot_20220903-101616 1](https://user-images.githubusercontent.com/3448386/188264330-e699474f-5f18-471b-bf04-befe204bba02.png)

**Comment by rogercreagh** [comment]
Well that certainly confused me. How do I get it to make a noise like a Melodeon again without having to uninstall and re-install - is it just an accordion with a different arrangement of keys? (So you have to select Accordion in the list?)
